# Generated by Django 5.2.6 on 2025-09-10 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='E.g., 00700.HK (Tencent), AAPL (Apple)', max_length=20, unique=True, verbose_name='Stock Code')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Stock Name')),
                ('market', models.CharField(blank=True, help_text='E.g., HK (Hong Kong), US (United States)', max_length=10, null=True, verbose_name='Market')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='stocks_stoc_code_d5ca83_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('open', models.FloatField(verbose_name='Open Price')),
                ('high', models.FloatField(verbose_name='High Price')),
                ('low', models.FloatField(verbose_name='Low Price')),
                ('close', models.FloatField(verbose_name='Close Price')),
                ('volume', models.BigIntegerField(help_text='Unit: shares', verbose_name='Volume')),
                ('adjusted_close', models.FloatField(blank=True, null=True, verbose_name='Adjusted Close Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stocks.stock', verbose_name='Stock')),
            ],
            options={
                'verbose_name': 'Stock Price',
                'verbose_name_plural': 'Stock Prices',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['stock', 'date'], name='stocks_stoc_stock_i_86bebf_idx')],
                'unique_together': {('stock', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StrategySignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Signal Date')),
                ('signal_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=10, verbose_name='Signal Type')),
                ('price', models.FloatField(help_text='Close price when signal generated', verbose_name='Signal Price')),
                ('ma_short', models.FloatField(verbose_name='Short-term MA Value')),
                ('ma_long', models.FloatField(verbose_name='Long-term MA Value')),
                ('short_window', models.PositiveIntegerField(default=5, verbose_name='Short Window')),
                ('long_window', models.PositiveIntegerField(default=20, verbose_name='Long Window')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='stocks.stock', verbose_name='Stock')),
            ],
            options={
                'verbose_name': 'Strategy Signal',
                'verbose_name_plural': 'Strategy Signals',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['stock', 'date'], name='stocks_stra_stock_i_a5d7d0_idx')],
                'unique_together': {('stock', 'date', 'short_window', 'long_window')},
            },
        ),
    ]
